[general]
static=yes
writeprotect=no

[default]
exten => 1001,1,Answer()
exten => 1001,2,Dial(PJSIP/1001,20)
exten => 1001,3,Hangup()

exten => 1002,1,Answer()
exten => 1002,2,Dial(PJSIP/1002,20)
exten => 1002,3,Hangup()

exten => 100,1,Answer()
exten => 100,2,Wait(1)
exten => 100,3,Playback(hello-world)
exten => 100,4,Hangup()
