[general]
context=default
bindport=5060
bindaddr=0.0.0.0
transport=udp

[1001]
type=friend
username=1001
secret=1001
context=default
host=dynamic
callerid=Usuario 1001

[1002]
type=friend
username=1002
secret=1002
context=default
host=dynamic
callerid=Usuario 1002
